USE GD2C2025;
GO

-----------------------------------------------------------------------------------------
-- 0. LIMPIEZA INICIAL (Para poder re-ejecutar el script)
-----------------------------------------------------------------------------------------
DROP PROCEDURE IF EXISTS LOS_DESNORMALIZADOS.BI_migrar_hechos_encuestas;
DROP PROCEDURE IF EXISTS LOS_DESNORMALIZADOS.BI_migrar_hechos_detalle_factura;
DROP PROCEDURE IF EXISTS LOS_DESNORMALIZADOS.BI_migrar_hechos_finales;
DROP PROCEDURE IF EXISTS LOS_DESNORMALIZADOS.BI_migrar_hechos_inscripciones;
DROP PROCEDURE IF EXISTS LOS_DESNORMALIZADOS.BI_migrar_dimensiones;
DROP FUNCTION IF EXISTS LOS_DESNORMALIZADOS.BI_obtener_edad;
DROP FUNCTION IF EXISTS LOS_DESNORMALIZADOS.BI_obtener_rango_etario;
DROP FUNCTION IF EXISTS LOS_DESNORMALIZADOS.BI_alumno_aprobo;

-- Borrar Vistas
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_10_indice_satisfaccion;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_09_ingresos_categoria;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_08_morosidad;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_07_desvio_pagos;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_06_ausentismo;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_05_nota_promedio_finales;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_04_tiempo_promedio_finalizacion;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_03_desempenio_cursada;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_02_tasa_rechazo;
DROP VIEW IF EXISTS LOS_DESNORMALIZADOS.BI_vista_01_categorias_turnos_solicitados;

-- Borrar Tablas de Hechos
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_hechos_encuestas;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_hechos_detalle_factura;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_hechos_finales;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_hechos_inscripciones;

-- Borrar Tablas de Dimensiones
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_bloque_satisfaccion;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_rango_etario_alumnos;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_rango_etario_profesores;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_medio_pago;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_estado_inscripcion;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_categoria_curso;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_turno_curso;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_sede;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_profesor;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_alumno;
DROP TABLE IF EXISTS LOS_DESNORMALIZADOS.BI_dim_tiempo;

GO